# -*- coding: utf-8 -*-
"""DataSynthesizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nnl6xSXORK-UIcPaTH9fQ2LZz-Flkc-R
"""

from google.colab import drive
import sys

# Mount Google Drive
drive.mount('/content/drive', force_remount=True)

# Get the absolute path of the current folder
abspath_curr = '/content/drive/My Drive/Colab Notebooks/capstone/'

import pandas as pd
df = pd.read_csv(abspath_curr + 'CABG_8yr_preselect41.csv', header=0)
#df = pd.read_csv(abspath_curr + 'CABG_5yr_preselect40.csv', header=0)

df.head()

df.shape

!pip install DataSynthesizer

import pandas as pd
from DataSynthesizer.DataDescriber import DataDescriber
from DataSynthesizer.DataGenerator import DataGenerator
from DataSynthesizer.lib.utils import display_bayesian_network

# Backup the original dataset
df_backup = df.copy()

# Specify categorical attributes
categorical_attributes = {'OTHBLEED':True,
                          "PUFYEAR": True,
                          "SEX": True,
                          "RACE_NEW": True,
                          "INOUT": True,
                          "ANESTHES": True,
                          "DIABETES": True,
                          "SMOKE": True,
                          "DYSPNEA": True,
                          "FNSTATUS2": True,
                          "VENTILAT": True,
                          "HXCOPD": True,
                          "ASCITES": True,
                          "HXCHF": True,
                          "HYPERMED": True,
                          "RENAFAIL": True,
                          "DIALYSIS": True,
                          "DISCANCR": True,
                          "WNDINF": True,
                          "STEROID": True,
                          "WTLOSS": True,
                          "BLEEDIS": True,
                          "TRANSFUS": True,
                          "EMERGNCY": True,
                          "ASACLAS": True
                          }

# Define privacy settings
epsilon = 0.1
degree_of_bayesian_network = 2
num_tuples_to_generate = 1000

# Initialize DataDescriber with category threshold
describer = DataDescriber(category_threshold=5)

# Describe the dataset to create a Bayesian network
describer.describe_dataset_in_correlated_attribute_mode(dataset_file='/content/drive/My Drive/Colab Notebooks/capstone/CABG_8yr_preselect41.csv',
                                                        epsilon=epsilon,
                                                        k=degree_of_bayesian_network,
                                                        attribute_to_is_categorical=categorical_attributes
                                                        )

# Save dataset description to a JSON file
description_file = 'CABG_description.json'
describer.save_dataset_description_to_file(abspath_curr + description_file)
# Display the Bayesian network
display_bayesian_network(describer.bayesian_network)

generator = DataGenerator()
generator.generate_dataset_in_correlated_attribute_mode(num_tuples_to_generate, abspath_curr + description_file)
# Save synthetic data to a CSV file
synthetic_data_file = 'CABG_synthetic_Bayesian_8yr.csv'
generator.save_synthetic_data(abspath_curr + synthetic_data_file)

df_synthetic = pd.read_csv(synthetic_data_file)